name: Build macOS .app GUI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .app Bundle
        run: pyinstaller --windowed --name ytglp ytglp.py

      - name: Upload .app Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ytglp-app
          path: dist/ytglp.app
